name       : gnome-doc-utils
version    : 0.20.10
release    : 8
source     :
    - https://download.gnome.org/sources/gnome-doc-utils/0.20/gnome-doc-utils-0.20.10.tar.xz : cb0639ffa9550b6ddf3b62f3b1add92fb92ab4690d351f2353cffe668be8c4a6
homepage   : https://live.gnome.org/GnomeDocUtils
license    : LGPL-2.0
component  : desktop.gnome.doc
summary    : GNOME Documentation Utilities
description: |
    The GNOME Doc Utils package is a collection of documentation utilities for the GNOME project. Notably, it contains utilities for building documentation and all auxiliary files in your source tree, and it contains the DocBook XSLT stylesheets that were once distributed with Yelp.
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(rarian)
patterns   :
    - /*
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
